public class User {

    //User Vairables
    private int level;
    private double money;
    private double attack;
    private double speed; 
    private double health;
    private double defense;

    public void User() {

        //initalizies the variables with starting scores
        level = 0;
        money = 0.0;
        attack = 0.0;
        speed = 0.0;
        health = 0.0;
        defense = 0.0;
    }
}